[package]
name = "effects"
publish = false
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
demo-shared.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-util.workspace = true
gloo-timers.workspace = true
ratcn = { workspace = true, features = ["ratzilla"] }
ratzilla.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ratcn = { workspace = true, features = ["crossterm"] }
ratatui = { workspace = true, features = ["crossterm"] }
ureq.workspace = true
